// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    FormOutlined: typeof import('@ant-design/icons-vue')['FormOutlined']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    PoweroffOutlined: typeof import('@ant-design/icons-vue')['PoweroffOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
